#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Run Homebrew through the Brewfile
if command -v brew >/dev/null 2>&1
then
  echo "› brew bundle"
  brew bundle
else
  echo "brew not installed; skipping."
fi

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
